spring.application.name=GatewayMS
server.port=9000
# Allow CORS for 3000 origin only
# ✅ In short:
# DedupeResponseHeader → Fix duplicate CORS header issues.
# allowedOrigins → Allow your frontend to call backend APIs.
# allowedMethods → Defines which HTTP methods are allowed.
# allowedHeaders → Allow all headers (esp. Authorization for tokens).

spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin RETAIN_UNIQUE
spring.cloud.gateway.globalcors.corsConfigurations[/**].allowedOrigins=http://localhost:3000
spring.cloud.gateway.globalcors.corsConfigurations[/**].allowedMethods=GET,POST,PUT,DELETE
spring.cloud.gateway.globalcors.corsConfigurations[/**].allowedHeaders=*


# UserMS Configuration
spring.cloud.gateway.routes[0].id=UserMS
spring.cloud.gateway.routes[0].uri=http://localhost:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/user/**
spring.cloud.gateway.routes[0].filters[0]=TokenFilter

