spring.application.name=pharmacyMS

server.port=9300
spring.datasource.url=jdbc:mysql://localhost:3306/pharmacydb
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update



MEDICINE_ALREADY_EXISTS=Medicine with the same name and dosage  already exists.
MEDICINE_NOT_FOUND= Medicine not found