package com.hms.pharmacy.entity;

public enum MedicineCategory {
    ANTIBIOTIC, ANALGESIC, ANTISEPTIC, VACCINE, ANTIVIRAL, ANTIINFLAMMATORY, ANTIFUNGAL, DIURETIC, 
    ANTIDEPRESSANT, ANTIPSYCHOTIC, SEDATIVE, ANTIHISTAMINE, VITAMIN, 
    MINERAL_SUPPLEMENT, HORMONE, CHEMOTHERAPEUTIC
}
